### 
GET http://localhost:9000/api


### 
GET http://localhost:9000/api/restaurants/

### 
GET http://localhost:9000/api/restaurants/55cba2476c522cafdb053add


### 
GET http://localhost:9000/api/neighborhoods

### 
GET http://localhost:9000/api/neighborhoods/55cb9c666c522cafdb053a1a


###
POST http://localhost:9000/api/currentNeighborHood
Content-Type: application/json

{
    "long": -73.93414657,
    "lat": 40.82302903
}



###
POST http://localhost:9000/api/findAllRes
Content-Type: application/json

{
  
    "long": -73.93414657,
    "lat": 40.82302903
  
}


###
POST http://localhost:9000/api/findResInDistance
Content-Type: application/json

{
  
    "long": -73.93414657,
    "lat": 40.82302903
  
}



